<?php
// Music archive API.
//   getData.php?action=whoami        -> login state (allowed IPs are signed in automatically)
//   getData.php?action=login         -> POST {user, password}
//   getData.php?action=logout        -> sign out
//   getData.php?action=albums        -> album list (from .meta.json caches)
//   getData.php?action=album&id=Artist/Album -> album tracks with URLs per format (alac/flac/aac)
//   getData.php?action=coverSearch&id=X   -> cover candidates from MusicBrainz / Cover Art Archive
//   getData.php?action=coverSave&id=X     -> POST {mbid} downloads the chosen cover (needs the 'cover' right)
session_name('userSession');   // instead of the generic PHPSESSID (the domain is shared with other apps)
session_start();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');   // responses must not be cached – data changes on disk
set_time_limit(0);   // reading tags of a large archive may exceed the default limit

$ROOT = __DIR__;
$SRC = "$ROOT/cd/alac";      // masters ripped by Apple Music (ALAC)
$COVERS = "$ROOT/covers";
$DERIVED = ["flac" => "$ROOT/cd/flac", "aac" => "$ROOT/cd/aac"];   // generated by transcode.sh
$COVER_SIZE = 400;
$MB_USER_AGENT = 'music-archive/1.0 (https://github.com/mitrenga/music)';   // MusicBrainz requires an identifying User-Agent
$AUDIO_EXT = ['m4a', 'mp3', 'flac', 'ogg', 'opus', 'wav'];

// users and allowed-IPs configuration (same format as the gallery project)
$CONFIG_FILE = __DIR__ . '/config.json';

// short-lived password-reset tokens; kept outside the web root so they can never be
// downloaded, with an install-specific name so two installs cannot collide
$RESET_FILE = sys_get_temp_dir() . '/music-reset-' . md5(__DIR__) . '.json';
$RESET_TTL = 3600;   // reset link validity in seconds

$action = $_GET['action'] ?? 'albums';

// ---- authentication (shared logic in authLib.php) ----
require __DIR__ . '/authLib.php';

$config = is_file($CONFIG_FILE) ? json_decode(file_get_contents($CONFIG_FILE), true) : null;
$user = resolveAuthUser($config);
$authenticated = $user !== null;
$rights = resolveRights($config, $user);

// 403 unless the signed-in user has the given right ("move", "delete", …)
function requireRight(array $rights, string $right): void {
    if (!in_array($right, $rights, true)) {
        http_response_code(403);
        echo json_encode(['error' => "missing '$right' permission"]);
        exit;
    }
}

if ($action === 'whoami') {
    echo json_encode([
        'auth' => $authenticated,
        'user' => $_SESSION['user'] ?? null,
        'rights' => $rights,
        'title' => $config['title'] ?? null,   // application name from config.json
    ]);
    exit;
}

if ($action === 'login') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    $u = (string)($body['user'] ?? '');
    $p = (string)($body['password'] ?? '');
    foreach (($config['users'] ?? []) as $usr) {
        if (hash_equals((string)$usr['user'], $u) && hash_equals((string)$usr['password'], $p)) {
            session_regenerate_id(true);
            $_SESSION['user'] = $u;
            echo json_encode(['auth' => true, 'user' => $u, 'rights' => resolveRights($config, $u)]);
            exit;
        }
    }
    http_response_code(401);
    echo json_encode(['auth' => false, 'error' => 'invalid username or password']);
    exit;
}

if ($action === 'logout') {
    session_destroy();
    echo json_encode(['auth' => false]);
    exit;
}

// POST {email} – e-mails a password-reset link. The response is always the same
// so it is impossible to probe which e-mail addresses exist.
if ($action === 'resetRequest') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    $email = trim((string)($body['email'] ?? ''));

    $tokens = is_file($RESET_FILE) ? (json_decode(file_get_contents($RESET_FILE), true) ?: []) : [];
    $now = time();
    $tokens = array_filter($tokens, fn($t) => $t['expires'] > $now);   // drop expired tokens

    // at most 5 pending requests per IP – a cheap brake on mail spamming
    $ip = $_SERVER['REMOTE_ADDR'] ?? '';
    $fromIp = count(array_filter($tokens, fn($t) => ($t['ip'] ?? '') === $ip));

    if ($email !== '' && $fromIp < 5) {
        foreach (($config['users'] ?? []) as $usr) {
            if (($usr['email'] ?? '') !== '' && strcasecmp($usr['email'], $email) === 0) {
                $token = bin2hex(random_bytes(32));
                $tokens[$token] = ['user' => $usr['user'], 'expires' => $now + $RESET_TTL, 'ip' => $ip];

                // link back to the application, derived from the current request
                $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
                $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
                $link = $scheme . '://' . $host
                      . rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? '/'), '/') . "/?reset=$token";

                $title = $config['title'] ?? 'Music';
                $subject = '=?UTF-8?B?' . base64_encode("$title – password reset") . '?=';
                $message = "Your user name: {$usr['user']}\n\n"
                         . "To set a new password open this link (valid for 1 hour):\n\n$link\n\n"
                         . "If you did not request a password reset, ignore this e-mail.";
                if (!empty($config['smtp']['host'])) {
                    smtpSend($config['smtp'], $email, $subject, $message);
                } else {   // fallback: local MTA via mail()
                    $from = 'music@' . preg_replace('/:\d+$/', '', $host);
                    mail($email, $subject, $message,
                        "From: $from\r\nContent-Type: text/plain; charset=utf-8");
                }
                break;
            }
        }
    }

    file_put_contents($RESET_FILE, json_encode($tokens), LOCK_EX);
    echo json_encode(['ok' => true]);
    exit;
}

// POST {token, password} – sets a new password for the user the token belongs to
if ($action === 'resetPassword') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    $token = (string)($body['token'] ?? '');
    $password = (string)($body['password'] ?? '');

    $tokens = is_file($RESET_FILE) ? (json_decode(file_get_contents($RESET_FILE), true) ?: []) : [];
    $entry = $tokens[$token] ?? null;
    if ($entry === null || $entry['expires'] < time()) {
        http_response_code(400);
        echo json_encode(['error' => 'invalid or expired link']);
        exit;
    }
    if (strlen($password) < 8) {
        http_response_code(400);
        echo json_encode(['error' => 'password too short (min 8 characters)']);
        exit;
    }

    $saved = false;
    foreach (($config['users'] ?? []) as $i => $usr) {
        if ($usr['user'] === $entry['user']) {
            $config['users'][$i]['password'] = $password;
            $saved = file_put_contents($CONFIG_FILE,
                json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                LOCK_EX) !== false;
            break;
        }
    }

    unset($tokens[$token]);   // the token is single-use
    file_put_contents($RESET_FILE, json_encode($tokens), LOCK_EX);

    if (!$saved) {   // user removed from config meanwhile, or config.json is not writable
        http_response_code(500);
        echo json_encode(['error' => 'could not save the new password']);
        exit;
    }
    echo json_encode(['ok' => true]);
    exit;
}

// all other actions require authentication
if (!$authenticated) {
    http_response_code(401);
    echo json_encode(['error' => 'not authenticated']);
    exit;
}

// the session is read-only from here on – release the lock so parallel requests don't wait
session_write_close();

// filesystem path -> URL: every segment percent-encoded, otherwise "#" or "'"
// in an artist/album/track name would break the URL
function urlPath(string ...$segments): string {
    return implode('/', array_map('rawurlencode', $segments));
}

// audio files of an album directory, sorted by name (NN Title.ext)
function audioFiles(string $dir, array $ext): array {
    $files = [];
    foreach (scandir($dir) as $f) {
        if ($f[0] === '.' || !is_file("$dir/$f")) continue;
        if (in_array(strtolower(pathinfo($f, PATHINFO_EXTENSION)), $ext)) $files[] = $f;
    }
    sort($files, SORT_NATURAL | SORT_FLAG_CASE);
    return $files;
}

// "3/9" -> 3, "3" -> 3, "" -> null
function tagInt(?string $v): ?int {
    if ($v === null || !preg_match('/^\s*(\d+)/', $v, $m)) return null;
    return (int)$m[1];
}

// tags of one file via ffprobe (keys are lower-cased; ffprobe emits them in
// varying case depending on the container)
function probeTrack(string $path): array {
    $json = shell_exec('ffprobe -v error -select_streams a:0 -show_entries stream=codec_name:format=duration:format_tags -of json '
                     . escapeshellarg($path) . ' 2>/dev/null');
    $probe = json_decode((string)$json, true) ?? [];
    $fmt = $probe['format'] ?? [];
    $tags = array_change_key_case($fmt['tags'] ?? [], CASE_LOWER);
    return [
        'duration' => (int)round((float)($fmt['duration'] ?? 0)),
        'codec' => $probe['streams'][0]['codec_name'] ?? null,   // alac, aac, mp3, flac, …
        'title' => $tags['title'] ?? null,
        'artist' => $tags['artist'] ?? null,
        'albumArtist' => $tags['album_artist'] ?? $tags['albumartist'] ?? null,
        'album' => $tags['album'] ?? null,
        'track' => tagInt($tags['track'] ?? null),
        'disc' => tagInt($tags['disc'] ?? null),
        'date' => $tags['date'] ?? $tags['year'] ?? null,
        'genre' => $tags['genre'] ?? null,
        'composer' => $tags['composer'] ?? null,
    ];
}

const META_VERSION = 2;

// Album metadata from the .meta.json cache in the album directory; rebuilt
// when the cache is missing, older than any audio file, or the file list
// changed. Falls back to directory/file names when tags are missing.
function albumMeta(string $artistDir, string $albumDir, string $dir, array $ext): ?array {
    $files = audioFiles($dir, $ext);
    if (!$files) return null;
    $cacheFile = "$dir/.meta.json";
    $newest = 0;
    foreach ($files as $f) $newest = max($newest, filemtime("$dir/$f"));

    if (is_file($cacheFile)) {
        $meta = json_decode(file_get_contents($cacheFile), true);
        if (is_array($meta) && ($meta['version'] ?? 0) === META_VERSION
                && filemtime($cacheFile) >= $newest
                && array_column($meta['tracks'], 'file') === $files) {
            return $meta;
        }
    }

    $tracks = [];
    foreach ($files as $i => $f) {
        $t = probeTrack("$dir/$f");
        // "NN Title.ext" – file name is the fallback for title and track number
        $base = pathinfo($f, PATHINFO_FILENAME);
        $fromName = preg_match('/^(\d+)[\s._-]+(.*)$/', $base, $m) ? $m : [null, null, $base];
        $tracks[] = [
            'file' => $f,
            'no' => $t['track'] ?? ($fromName[1] !== null ? (int)$fromName[1] : $i + 1),
            'disc' => $t['disc'] ?? 1,
            'title' => $t['title'] ?? $fromName[2],
            'artist' => $t['artist'],
            'composer' => $t['composer'],
            'duration' => $t['duration'],
            'codec' => $t['codec'],
            '_album' => $t['album'], '_albumArtist' => $t['albumArtist'],
            '_date' => $t['date'], '_genre' => $t['genre'],
        ];
    }
    usort($tracks, fn($a, $b) => [$a['disc'], $a['no']] <=> [$b['disc'], $b['no']]);

    // album-level values: the most common tag across tracks, else the directory name
    $common = function (string $key) use ($tracks): ?string {
        $vals = array_filter(array_column($tracks, $key), fn($v) => $v !== null && $v !== '');
        if (!$vals) return null;
        $counts = array_count_values($vals);
        arsort($counts);
        return (string)array_key_first($counts);
    };
    $title = $albumDir;
    if (is_file("$dir/.title") && ($t = trim(file_get_contents("$dir/.title"))) !== '') $title = $t;
    elseif (($t = $common('_album')) !== null) $title = $t;

    $artists = array_unique(array_filter(array_column($tracks, 'artist')));
    $artist = $common('_albumArtist') ?? (count($artists) === 1 ? reset($artists) : null) ?? $artistDir;
    $date = $common('_date');

    $meta = [
        'version' => META_VERSION,
        'id' => "$artistDir/$albumDir",
        'artist' => $artist,
        'title' => $title,
        'year' => $date !== null && preg_match('/\d{4}/', $date, $m) ? (int)$m[0] : null,
        'genre' => $common('_genre'),
        'compilation' => count($artists) > 1,
        'discs' => max(array_column($tracks, 'disc')),
        'duration' => array_sum(array_column($tracks, 'duration')),
        'tracks' => array_map(fn($t) => array_filter($t, fn($k) => $k[0] !== '_', ARRAY_FILTER_USE_KEY), $tracks),
    ];
    // a failed write only costs a re-probe next time (fix-perms.sh makes the directory writable)
    @file_put_contents($cacheFile,
        json_encode($meta, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), LOCK_EX);
    return $meta;
}

// cover image in the album directory (cover.jpg, folder.png, …) as an absolute path, or null
function coverFile(string $dir): ?string {
    foreach (['cover.jpg', 'cover.jpeg', 'cover.png', 'folder.jpg', 'folder.png'] as $c) {
        if (is_file("$dir/$c")) return "$dir/$c";
    }
    return null;
}

// ['cover' => URL of the original, 'thumb' => URL of the 400×400 thumbnail] or nulls;
// the thumbnail in covers/<Artist>/<Album>.jpg is (re)generated when missing or outdated
function albumCover(string $artistDir, string $albumDir, string $dir): array {
    global $COVERS, $COVER_SIZE;
    $file = coverFile($dir);
    if ($file === null) return ['cover' => null, 'thumb' => null];
    $thumbAbs = "$COVERS/$artistDir/$albumDir.jpg";
    if (!is_file($thumbAbs) || filemtime($thumbAbs) < filemtime($file)) {
        @mkdir("$COVERS/$artistDir", 0775, true);
        exec(sprintf('convert %s -auto-orient -thumbnail %dx%d^ -gravity center -extent %dx%d -quality 85 %s 2>/dev/null',
            escapeshellarg($file), $COVER_SIZE, $COVER_SIZE, $COVER_SIZE, $COVER_SIZE, escapeshellarg($thumbAbs)));
    }
    return [
        'cover' => urlPath('cd', 'alac', $artistDir, $albumDir, basename($file)),
        'thumb' => is_file($thumbAbs) ? urlPath('covers', $artistDir, "$albumDir.jpg") : null,
    ];
}

// HTTPS GET with the MusicBrainz User-Agent; [status, body] – body null on network failure
function httpGet(string $url, int $timeout = 15): array {
    global $MB_USER_AGENT;
    $ctx = stream_context_create(['http' => [
        'header' => "User-Agent: $MB_USER_AGENT\r\nAccept: application/json, image/*\r\n",
        'timeout' => $timeout, 'follow_location' => 1, 'max_redirects' => 5, 'ignore_errors' => true,
    ]]);
    $body = @file_get_contents($url, false, $ctx);
    $status = 0;
    foreach ($http_response_header ?? [] as $h) {   // the last status line wins (after redirects)
        if (preg_match('#^HTTP/\S+\s+(\d{3})#', $h, $m)) $status = (int)$m[1];
    }
    return [$status, $body === false ? null : $body];
}

// "Artist/Album" from ?id=, validated against the archive (no escaping cd/)
function albumPath(string $src, string $id): ?array {
    $parts = explode('/', $id);
    if (count($parts) !== 2 || $parts[0] === '' || $parts[1] === ''
            || basename($parts[0]) !== $parts[0] || basename($parts[1]) !== $parts[1]
            || $parts[0][0] === '.' || $parts[1][0] === '.'
            || !is_dir("$src/{$parts[0]}/{$parts[1]}")) return null;
    return $parts;
}

if ($action === 'albums') {
    $albums = [];
    foreach (scandir($SRC) as $a) {
        if ($a[0] === '.' || !is_dir("$SRC/$a")) continue;
        foreach (scandir("$SRC/$a") as $b) {
            if ($b[0] === '.' || !is_dir("$SRC/$a/$b")) continue;
            $meta = albumMeta($a, $b, "$SRC/$a/$b", $AUDIO_EXT);
            if ($meta === null) continue;   // directory without audio files
            $albums[] = [
                'id' => $meta['id'],
                'artist' => $meta['artist'],
                'title' => $meta['title'],
                'year' => $meta['year'],
                'genre' => $meta['genre'],
                'tracks' => count($meta['tracks']),
                'duration' => $meta['duration'],
            ] + albumCover($a, $b, "$SRC/$a/$b");
        }
    }
    // artist, then year, then title
    usort($albums, fn($x, $y) => [mb_strtolower($x['artist']), $x['year'] ?? 9999, mb_strtolower($x['title'])]
                             <=> [mb_strtolower($y['artist']), $y['year'] ?? 9999, mb_strtolower($y['title'])]);
    echo json_encode(['albums' => $albums], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

if ($action === 'album') {
    $parts = albumPath($SRC, (string)($_GET['id'] ?? ''));
    $meta = $parts ? albumMeta($parts[0], $parts[1], "$SRC/{$parts[0]}/{$parts[1]}", $AUDIO_EXT) : null;
    if ($meta === null) {
        http_response_code(404);
        echo json_encode(['error' => 'album not found']);
        exit;
    }
    [$a, $b] = $parts;
    $meta += albumCover($a, $b, "$SRC/$a/$b");
    // per-format URLs of the derived copies; null while a copy does not exist yet
    $missing = false;
    foreach ($meta['tracks'] as &$t) {
        $base = pathinfo($t['file'], PATHINFO_FILENAME);
        $master = filemtime("$SRC/$a/$b/{$t['file']}");
        $t['src'] = urlPath('cd', 'alac', $a, $b, $t['file']);   // the ALAC master
        $t['formats'] = ['alac' => $t['src']];   // playable directly in Safari
        foreach (['flac' => "$base.flac", 'aac' => "$base.m4a"] as $fmt => $name) {
            $path = "{$DERIVED[$fmt]}/$a/$b/$name";
            if (is_file($path) && filemtime($path) >= $master) {
                $t['formats'][$fmt] = urlPath('cd', $fmt, $a, $b, $name);
            } else {
                $t['formats'][$fmt] = null;
                $missing = true;
            }
        }
    }
    unset($t, $meta['version']);
    // derive the missing copies in the background (transcode.sh skips an album already running)
    if ($missing) {
        $meta['converting'] = true;
        if (!is_dir("{$DERIVED['aac']}/$a/$b/.lock")) {
            exec('nohup ' . escapeshellarg("$ROOT/transcode.sh") . ' ' . escapeshellarg("$SRC/$a/$b") . ' > /dev/null 2>&1 &');
        }
    }
    echo json_encode($meta, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

// Cover candidates: MusicBrainz releases matching artist + album. The client
// previews https://coverartarchive.org/release/<mbid>/front-250 directly (releases
// without artwork simply fail to load), nothing is saved here.
if ($action === 'coverSearch') {
    $parts = albumPath($SRC, (string)($_GET['id'] ?? ''));
    $meta = $parts ? albumMeta($parts[0], $parts[1], "$SRC/{$parts[0]}/{$parts[1]}", $AUDIO_EXT) : null;
    if ($meta === null) {
        http_response_code(404);
        echo json_encode(['error' => 'album not found']);
        exit;
    }
    // optional overrides let the user refine the query when the tags do not match
    $artist = trim((string)($_GET['artist'] ?? $meta['artist']));
    $title = trim((string)($_GET['title'] ?? $meta['title']));
    $lucene = fn(string $v) => '"' . addcslashes($v, '"\\') . '"';
    // a dot glued to a word ("Vol.1") breaks the MusicBrainz full-text search, so it becomes a space;
    // if the exact title finds nothing, the "Vol. N" suffix is dropped and the search is repeated
    $normalized = trim(preg_replace('/\s+/', ' ', preg_replace('/(?<=\w)\.(?=\w)/', ' ', $title)));
    $candidates = [$normalized];
    $stripped = trim(preg_replace('/[\s,:-]*\b(vol|volume|part|pt)\b\.?\s*\d+\s*$/i', '', $normalized));
    if ($stripped !== '' && $stripped !== $normalized) $candidates[] = $stripped;
    foreach ($candidates as $t) {
        $query = 'release:' . $lucene($t) . ($artist !== '' ? ' AND artist:' . $lucene($artist) : '');
        [$status, $body] = httpGet('https://musicbrainz.org/ws/2/release/?fmt=json&limit=12&query=' . rawurlencode($query));
        if ($status === 200 && !empty(json_decode($body, true)['releases'])) break;
    }
    if ($status !== 200 || $body === null) {
        http_response_code(502);
        echo json_encode(['error' => "MusicBrainz request failed (HTTP $status)"]);
        exit;
    }
    $candidates = [];
    foreach ((json_decode($body, true)['releases'] ?? []) as $r) {
        $candidates[] = [
            'mbid' => $r['id'],
            'title' => $r['title'] ?? '',
            'artist' => implode('', array_map(fn($c) => ($c['name'] ?? '') . ($c['joinphrase'] ?? ''), $r['artist-credit'] ?? [])),
            'date' => $r['date'] ?? null,
            'country' => $r['country'] ?? null,
            'format' => implode(' + ', array_filter(array_map(fn($m) => $m['format'] ?? null, $r['media'] ?? []))),
            'tracks' => array_sum(array_map(fn($m) => $m['track-count'] ?? 0, $r['media'] ?? [])),
            'preview' => "https://coverartarchive.org/release/{$r['id']}/front-250",
            'large' => "https://coverartarchive.org/release/{$r['id']}/front-500",
        ];
    }
    echo json_encode(['artist' => $artist, 'title' => $title, 'candidates' => $candidates], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

// POST {mbid} – downloads the front cover of the chosen release into the album
// directory as cover.jpg (replacing an existing one) and refreshes the thumbnail
if ($action === 'coverSave') {
    requireRight($rights, 'cover');
    $parts = albumPath($SRC, (string)($_GET['id'] ?? ''));
    if ($parts === null) {
        http_response_code(404);
        echo json_encode(['error' => 'album not found']);
        exit;
    }
    [$a, $b] = $parts;
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    $mbid = strtolower((string)($body['mbid'] ?? ''));
    if (!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/', $mbid)) {
        http_response_code(400);
        echo json_encode(['error' => 'invalid release id']);
        exit;
    }
    // only the Cover Art Archive is contacted – the id is validated, so no arbitrary URL can be fetched
    [$status, $img] = httpGet("https://coverartarchive.org/release/$mbid/front-1200", 60);
    if ($status !== 200 || $img === null || strlen($img) < 1000) {
        http_response_code(502);
        echo json_encode(['error' => "cover download failed (HTTP $status)"]);
        exit;
    }
    $dir = "$SRC/$a/$b";
    $tmp = "$dir/.cover.download";
    if (@file_put_contents($tmp, $img, LOCK_EX) === false) {
        http_response_code(500);
        echo json_encode(['error' => 'album directory is not writable (run fix-perms.sh)']);
        exit;
    }
    $info = @getimagesize($tmp);
    if ($info === false || !in_array($info[2], [IMAGETYPE_JPEG, IMAGETYPE_PNG, IMAGETYPE_GIF, IMAGETYPE_WEBP], true)) {
        @unlink($tmp);
        http_response_code(502);
        echo json_encode(['error' => 'downloaded file is not an image']);
        exit;
    }
    // normalize to JPEG (max 1200 px) so every album carries a plain cover.jpg
    exec(sprintf('convert %s -auto-orient -resize 1200x1200\> -quality 90 %s 2>/dev/null',
        escapeshellarg($tmp), escapeshellarg("$dir/cover.jpg")), $out, $rc);
    @unlink($tmp);
    if ($rc !== 0 || !is_file("$dir/cover.jpg")) {
        http_response_code(500);
        echo json_encode(['error' => 'could not convert the cover (ImageMagick)']);
        exit;
    }
    foreach (['cover.jpeg', 'cover.png', 'folder.jpg', 'folder.png'] as $old) @unlink("$dir/$old");   // cover.jpg now wins
    @unlink("$COVERS/$a/$b.jpg");   // force a fresh thumbnail
    echo json_encode(['ok' => true] + albumCover($a, $b, $dir), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

http_response_code(400);
echo json_encode(['error' => 'unknown action']);

// Minimal SMTP client (implicit TLS + AUTH LOGIN) – works with Gmail using an
// app password; the "smtp" section of config.json provides host/port/user/password/from.
function smtpSend(array $smtp, string $to, string $subject, string $body): bool {
    $host = (string)($smtp['host'] ?? '');
    $port = (int)($smtp['port'] ?? 465);
    $from = (string)($smtp['from'] ?? $smtp['user'] ?? '');
    $fp = @stream_socket_client("ssl://$host:$port", $errno, $errstr, 15);
    if (!$fp) return false;
    stream_set_timeout($fp, 15);

    // reads a (possibly multi-line) reply and checks the status code
    $expect = function (string $code) use ($fp): bool {
        do { $line = fgets($fp, 1024); } while ($line !== false && isset($line[3]) && $line[3] === '-');
        return $line !== false && str_starts_with($line, $code);
    };
    $send = function (string $cmd, string $code) use ($fp, $expect): bool {
        fwrite($fp, $cmd . "\r\n");
        return $expect($code);
    };

    $body = preg_replace('/\r?\n/', "\r\n", $body);
    $body = str_replace("\r\n.", "\r\n..", $body);   // SMTP dot-stuffing

    $ok = $expect('220')
        && $send('EHLO music', '250')
        && $send('AUTH LOGIN', '334')
        && $send(base64_encode((string)($smtp['user'] ?? '')), '334')
        && $send(base64_encode((string)($smtp['password'] ?? '')), '235')
        && $send("MAIL FROM:<$from>", '250')
        && $send("RCPT TO:<$to>", '250')
        && $send('DATA', '354')
        && $send("From: $from\r\nTo: $to\r\nSubject: $subject\r\n"
               . "MIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n"
               . $body . "\r\n.", '250');
    fwrite($fp, "QUIT\r\n");
    fclose($fp);
    return $ok;
}

